---
title: "Untitled"
output: html_document
date: "2023-06-02"
---

```{r}
library(ggtree)
library(dplyr)
library(ggplot2)
library(gtable)
library(treeio)
library(ggnewscale)
library(tidyverse)
```

```{r mscquartets}
MSC_results <- read.csv("../output/mscquartets_output.txt")
MSC_results=MSC_results[,2:57]

alpha <- 0.05
numTests <- nrow(MSC_results) #249900

summary_MSC <- MSC_results %>% summarize(
  numSignificantAlpha = sum(p_T3 < alpha, na.rm=TRUE),#36405		
  numSignificantBonferroni = sum(p_T3 < alpha/numTests, na.rm=TRUE) #3132
)

# count number of occurrences where tip == 1, bonferroni level or p-val level reached
num_alpha05 <- c()
num_bonferroni <- c()

column_names <- colnames(MSC_results)
columnnameslength = length(column_names)

for (a in 1:columnnameslength) {
  num_alpha05[a] <- sum(MSC_results[ , a] == 1 & MSC_results$p_T3 < alpha)
  num_bonferroni[a] <- sum(MSC_results[ , a] == 1 & MSC_results$p_T3 < alpha/numTests)
}

for (a in 1:columnnameslength) {
  num_alpha05[a] <- sum(MSC_results[ , a] == 1 & MSC_results$p_T3 < alpha )
  num_bonferroni[a] <- sum(MSC_results[ , a] == 1  & MSC_results$p_T3 < alpha/numTests)
}

alpha05 = data.frame(taxa = column_names, frequency = num_alpha05)
alphabon = data.frame(taxa = column_names, frequency = num_bonferroni)

a05 = num_alpha05
ab = num_bonferroni

df_alpha_msc = data.frame(MSC= a05/summary_MSC$numSignificantAlpha
)

df_bonferroni_msc = data.frame(MSC = ab/summary_MSC$numSignificantBonferroni
)

# Scale values from 0 to 1 based on the maximum value of that test
columns = c( "MSC")
for (column in columns) {
  df_alpha_msc[column] = df_alpha_msc[column] / max(df_alpha_msc[column])
  df_bonferroni_msc[column] = df_bonferroni_msc[column] / max(df_bonferroni_msc[column])
}
```

```{r nanuq}
nanuq_results <- read.csv("../output/nanuq_output.csv", sep = " ")

alpha <- 0.05
numTests <- nrow(nanuq_results)

summary_nanuq <- nanuq_results %>% summarize(
  numSignificantAlpha = sum(p_T3 < alpha, na.rm=TRUE),
  numSignificantBonferroni = sum(p_T3 < alpha/numTests, na.rm=TRUE)
)

# count number of occurrences where tip == 1, bonferroni level or p-val level reached
num_alpha05 <- c()
num_bonferroni <- c()

column_names <- colnames(nanuq_results)
columnnameslength = length(column_names)

for (a in 1:columnnameslength) {
  num_alpha05[a] <- sum(nanuq_results[ , a] == 1 & nanuq_results$p_T3 < alpha)
  num_bonferroni[a] <- sum(nanuq_results[ , a] == 1 & nanuq_results$p_T3 < alpha/numTests)
}

for (a in 1:columnnameslength) {
  num_alpha05[a] <- sum(nanuq_results[ , a] == 1 & nanuq_results$p_T3 < alpha )
  num_bonferroni[a] <- sum(nanuq_results[ , a] == 1  & nanuq_results$p_T3 < alpha/numTests)
}

alpha05 = data.frame(taxa = column_names, frequency = num_alpha05)
alphabon = data.frame(taxa = column_names, frequency = num_bonferroni)

a05 = num_alpha05
ab = num_bonferroni

df_alpha_nanuq = data.frame(nanuq= a05/summary_nanuq$numSignificantAlpha
)

df_bonferroni_nanuq = data.frame(nanuq = ab/summary_nanuq$numSignificantBonferroni
)

# Scale values from 0 to 1 based on the maximum value of that test
columns = c( "nanuq")
for (column in columns) {
  df_alpha_nanuq[column] = df_alpha_nanuq[column] / max(df_alpha_nanuq[column])
  df_bonferroni_nanuq[column] = df_bonferroni_nanuq[column] / max(df_bonferroni_nanuq[column])
}
```

```{r plot}
df_rst = data.frame(df_alpha_msc[1:51,], df_alpha_nanuq[1:51,],
           df_bonferroni_msc[1:51,], df_bonferroni_nanuq[1:51,])
colnames(df_rst) = c("MSCQuartets Alpha", "NANUQ Alpha",
                     "MSCQuartets Bonferroni", "NANUQ Bonferroni")
df_rst$taxa = colnames(nanuq_results)[1:51]
df_rst %>%
  pivot_longer(!taxa, names_to = "D", values_to = "value") %>%
  ggplot(aes(D, taxa)) +
  geom_tile(aes(fill = value), colour = "black") +
  scale_fill_gradient(low = "white",high = "steelblue")
```

```{r}
# Create plot of proposed species tree, with aligned labels
p <- ggtree(tree, layout = "rectangular") + geom_tiplab(size=4, align=TRUE, linesize=.5) + 
     geom_label(aes(label=D), size=3.5, fill="thistle") + theme(legend.position = 'none')# + theme_tree2() 
p

# Create heatmaps for all tests next to tree visualization
alpha_plot <- gheatmap(p, df_alpha, offset=.2, width=1.2, colnames=TRUE, font.size = 3.5, colnames_angle = -0, legend_title="", low="white", high="#4a1486") +
  theme(legend.position = 'top') + scale_x_ggtree()
bonferroni_plot <- gheatmap(p, df_bonferroni, offset=.2, width=1.2, colnames=TRUE, font.size = 3.5, legend_title="", colnames_angle = -0, low="white", high="#4a1486") +
  theme(legend.position = 'top') + scale_x_ggtree()

# Display completed plots, and save
alpha_plot
bonferroni_plot
setwd("/Users/bjorner/GitHub/hybrid-detection-comparison/")
ggsave(filename = "alpha_bees_no_dufourea_ingt_ortree.png", plot = alpha_plot, width = 10, height = 8)
ggsave(filename = "bonferroni_bees_no_dufourea_ingt_ortree.png", plot = bonferroni_plot, width = 10, height = 8)
```

